config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'navigation#home'

  get 'basket', to: 'navigation#basket', as: 'basket'
  get 'choice', to: 'navigation#choice', as: 'choice'

  resources :access, only: [:index, :show, :destroy, :edit, :update]

  resources :main_photos, only: [:destroy]

  resources :main_descriptions, except: [:index] do
    resources :main_photos, only: [:new, :create]
  end

  resources :categories

  resources :ordered_products, except: [:create, :index]

  resources :products do
    resources :ordered_products, only: [:create]
  end

  resources :orders, only: [:show, :index, :edit, :update, :destroy] do
    resources :ordered_products, only: [:index]
    get 'fill', on: :new
    patch 'processing', on: :collection
  end

end

app/models/order.rb
# Order
class Order < ActiveRecord::Base
  include SharedModelMethods

  has_many :ordered_products, dependent: :destroy

  enum status: [:opened, :await, :considered, :delivery, :finished]

  validates :customer_name, presence: true, length: { maximum: 48 }, on: :update
  validates :phone, presence: true, length: { maximum: 48 }, on: :update
  validates :email, length: { maximum: 48 }, on: :update
  validates :description, presence: true, length: { maximum: 840 }, on: :update
end

app/controllers/orders_controller.rb
# Orders
class OrdersController < ApplicationController
  before_action :authenticate_user!, except: [:fill, :processing]

  def show
    if current_user.manager? || current_user.admin?
      @order = Order.find_by('id = ?', params[:id])
    elsif current_user.customer?
      @order = Order.find_by('id = ? and customer_login = ?',
                             params[:id],
                             current_user.email)
    else
      flash[:alert] = t(:who_are_you)
      redirect_to root_path
    end

    begin
      flash[:alert] = t(:order_existence_problem)
      redirect_to root_path
    end unless @order
  end

  def index
    if current_user.customer?
      @orders = Order.where('customer_login = ?',
                            current_user.email).numbering(params[:list], 10, 5)
      render 'customer_index'
    elsif current_user.manager?
      @orders = Order.all.numbering(params[:list], 10, 5)
      render 'manager_index'
    elsif current_user.admin?
      @orders = Order.all.numbering(params[:list], 10, 5)
      render 'index'
    else
      flash[:alert] = t(:who_are_you)
      redirect_to root_path
    end
    # authorize @orders[:objects]
  end

  def fill
    if @order = Order.find_by('customer_id = ? and status = ?',
                              cookies.signed[:customer_token],
                              Order.statuses[:opened])
      if user_signed_in?
        @order.customer_name = current_user.name
        @order.phone = current_user.phone
        @order.email = current_user.email
      end
      render 'fill'
    else
      flash[:alert] = t(:basket_is_empty)
      redirect_to products_path
    end
  end

  def edit
    if @order = Order.find_by('id = ?', params[:id])
      if current_user.customer? &&
         @order.await? && @order.customer_login == current_user.email
        render 'customer_edit'
      elsif current_user.manager?
        render 'manager_edit'
      elsif current_user.admin?
        render 'edit'
      else
        flash[:alert] = t(:order_change_problem)
        redirect_to root_path
      end
    else
      flash[:alert] = t(:order_existence_problem)
      redirect_to root_path
    end
  end

  def update
    @order = Order.find_by('id = ?', params[:id])
    if @order && (current_user.customer? || current_user.manager? ||
                                            current_user.admin?)
      if current_user.admin?
        handle @order.update_attributes(admin_attributes)
      elsif current_user.manager?
        handle @order.update_attributes(manager_attributes)
      elsif current_user.customer? &&
            @order.await? &&
            @order.customer_login == current_user.email
        handle @order.update_attributes(customer_attributes)
      else
        flash[:alert] = t(:who_are_you)
        redirect_to root_path
      end
    else
      flash[:alert] = t(:order_change_problem)
      redirect_to root_path
    end
  end

  def processing
    if @order = Order.find_by('customer_id = ? and status = ?',
                              cookies.signed[:customer_token],
                              Order.statuses[:opened])

      if user_signed_in?
        customer_login = current_user.email
      else
        customer_login = 'anonymous'
      end

      additional_information = { status: :await,
                                 customer_login: customer_login,
                                 order_name: @order.id.to_s +
                                             DateTime
                                             .now
                                             .strftime('_%d.%m.%Y') }

      if @order.update_attributes(customer_attributes
                                  .merge(additional_information))
        flash[:message] = t(:order_has_been_created,
                            order_name: @order.order_name)
        redirect_to root_path
      else
        flash[:alert] = t(:order_data_change_problem)
        render 'fill'
      end

    else
      flash[:alert] = t(:order_existence_problem)
      redirect_to root_path
    end
  end

  def destroy
    if current_user.admin?
      if @order = Order.find_by('id = ?', params[:id])
        if @order.destroy
          flash[:message] = t(:order_has_been_deleted,
                              order_name: @order.order_name)
          redirect_to orders_path
        else
          flash[:alert] = t(:order_delete_problem,
                            order_name: @order.order_name)
          redirect_to orders_path
        end
      else
        flash[:alert] = t(:order_existence_problem)
        redirect_to root_path
      end
    else
      flash[:alert] = t(:who_are_you)
      redirect_to root_path
    end
  end

  private

  def admin_attributes
    return unless !params[:order].blank? && params[:order].is_a?(Hash)
    params.require(:order).permit(:customer_name,
                                  :phone,
                                  :email,
                                  :description,
                                  :status_description,
                                  :status)
  end

  def manager_attributes
    return unless !params[:order].blank? && params[:order].is_a?(Hash)
    params.require(:order).permit(:status_description,
                                  :status)
  end

  def customer_attributes
    return unless !params[:order].blank? && params[:order].is_a?(Hash)
    params.require(:order).permit(:customer_name,
                                  :phone,
                                  :email,
                                  :description)
  end

  def handle(happened)
    if happened
      flash[:message] = t(:order_has_been_updated,
                          order_name: @order.order_name)
      redirect_to orders_path
    else
      flash[:alert] = t(:order_data_change_problem)
      render 'customer_edit' if current_user.customer?
      render 'manager_edit' if current_user.manager?
      render 'edit' if current_user.admin?
    end
  end
end

app/helpers/orders_helper.rb
# Orders
module OrdersHelper
end

app/views/orders/customer_edit.html.haml
.row
  .col-md-12
    .page-header
      %h3.text-center
        = t(:edit_order)

.row
  .col-md-12.text-center
    = render partial: 'shared/form_errors', locals: { object: @order }

.row
  .col-md-12
    = form_for @order do |f|

      .form-group
        = f.label :customer_name, t(:user_name)
        = f.text_field :customer_name, class: 'form-control'

      .form-group
        = f.label :phone, t(:phone)
        = f.text_field :phone, class: 'form-control'

      .form-group
        = f.label :email, t(:email)
        = f.email_field :email, class: 'form-control'

      .form-group
        = f.label :description, t(:description)
        = f.text_area :description, class: 'form-control'

      = f.submit t(:send), class: 'btn btn-primary'

app/views/orders/customer_index.html.haml
.row
  .col-md-12
    .page-header
      %h3.text-center
        = t(:all_customer_orders)

.row
  .col-md-12.text-center
    = will_be_numbered(orders_path, @orders[:pages])

.row
  .col-md-12
    %table.table.table-striped
      %thead
        %tr
          %th.text-center
            = t(:order_number)
          %th.text-center
            = t(:user_name)
          %th.text-center
            = t(:phone)
          %th.text-center
            = t(:email)
          %th.text-center
            = t(:description)
          %th.text-center
            = t(:status_description)
          %th.text-center
            = t(:order_status)
          %th.text-center
            = t(:action)

      %tbody
        - @orders[:objects].each do |o|
          %tr
            %td
              = link_to "#{o.order_name}", order_path(o)
            %td
              = o.customer_name
            %td
              = o.phone
            %td
              = o.email
            %td.long_words_breaker
              = o.description
            %td.long_words_breaker
              = o.status_description
            %td
              = t("status_#{o.status}")
            %td
              = link_to t(:show), order_ordered_products_path(o)
              %br
              - if o.await?
                = link_to t(:edit), edit_order_path(o)

app/views/orders/edit.html.haml
.row
  .col-md-12
    .page-header
      %h3.text-center
        = t(:edit_order)

.row
  .col-md-12.text-center
    = render partial: 'shared/form_errors', locals: { object: @order }

.row
  .col-md-12
    = form_for @order do |f|

      .form-group
        = f.label :customer_name, t(:user_name)
        = f.text_field :customer_name, class: 'form-control'

      .form-group
        = f.label :phone, t(:phone)
        = f.text_field :phone, class: 'form-control'

      .form-group
        = f.label :email, t(:email)
        = f.email_field :email, class: 'form-control'

      .form-group
        = f.label :description, t(:description)
        = f.text_area :description, class: 'form-control'

      .form-group
        = f.label :status_description, t(:status_description)
        = f.text_area :status_description, class: 'form-control'

      .form-group
        = f.label :status, t(:order_status)
        = f.select :status, |
                   Order |
                   .statuses |
                   .keys.to_a.map { |key| [t("status_#{key}"), key] }, |
                   class: 'form-control' |
      = f.submit t(:send), class: 'btn btn-primary'

app/views/orders/fill.html.haml
.row
  .col-md-12
    .page-header
      %h3.text-center
        = t(:leave_information_request)

.row
  .col-md-12.text-center
    = render partial: 'shared/form_errors', locals: { object: @order }

.row
  .col-md-12
    = form_for @order, url: processing_orders_path do |f|

      .form-group
        = f.label :customer_name, t(:user_name)
        = f.text_field :customer_name, class: 'form-control'

      .form-group
        = f.label :phone, t(:phone)
        = f.text_field :phone, class: 'form-control'

      .form-group
        = f.label :email, t(:email)
        = f.email_field :email, class: 'form-control'

      .form-group
        = f.label :description, t(:description)
        = f.text_area :description, class: 'form-control'

      = f.submit t(:send), class: 'btn btn-primary'

app/views/orders/index.html.haml
.row
  .col-md-12
    .page-header
      %h3.text-center
        = t(:all_orders)

.row
  .col-md-12.text-center
    = will_be_numbered(orders_path, @orders[:pages])

.row
  .col-md-12
    %table.table.table-striped
      %thead
        %tr
          %th.text-center
            = t(:order_number)
          %th.text-center
            = t(:user_name)
          %th.text-center
            = t(:phone)
          %th.text-center
            = t(:email)
          %th.text-center
            = t(:customer_login)
          %th.text-center
            = t(:description)
          %th.text-center
            = t(:customer_id)
          %th.text-center
            = t(:status_description)
          %th.text-center
            = t(:order_status)
          %th.text-center
            = t(:action)

      %tbody
        - @orders[:objects].each do |o|
          %tr
            %td
              = link_to "#{o.order_name}", order_path(o)
            %td
              = o.customer_name
            %td
              = o.phone
            %td
              = o.email
            %td
              = o.customer_login
            %td.long_words_breaker
              = o.description
            %td
              = 'Customer_id: ' + o.customer_id.to_s
            %td.long_words_breaker
              = o.status_description
            %td
              = t("status_#{o.status}")
            %td
              = link_to t(:show), order_ordered_products_path(o)
              %br
              = link_to t(:edit), edit_order_path(o)
              %br
              = link_to t(:delete), order_path(o), method: :delete,
                                    data: { confirm: t(:really_question) }

app/views/orders/manager_edit.html.haml
.row
  .col-md-12
    .page-header
      %h3.text-center
        = t(:edit_order)

.row
  .col-md-12.text-center
    = render partial: 'shared/form_errors', locals: { object: @order }

.row
  .col-md-12
    = form_for @order do |f|

      .form-group
        = f.label :customer_name, t(:user_name)
        = f.text_field :customer_name, readonly: true, class: 'form-control'

      .form-group
        = f.label :phone, t(:phone)
        = f.text_field :phone, readonly: true, class: 'form-control'

      .form-group
        = f.label :email, t(:email)
        = f.email_field :email, readonly: true, class: 'form-control'

      .form-group
        = f.label :description, t(:description)
        = f.text_area :description, readonly: true, class: 'form-control'

      .form-group
        = f.label :status_description, t(:status_description)
        = f.text_area :status_description, class: 'form-control'

      .form-group
        = f.label :status, t(:order_status)
        = f.select :status, |
                   Order.statuses. |
                   keys.to_a.map { |key| [t("status_#{key}"), key] }, |
                   class: 'form-control' |
      = f.submit t(:send), class: 'btn btn-primary'

app/views/orders/manager_index.html.haml
.row
  .col-md-12
    .page-header
      %h3.text-center
        = t(:all_orders)

.row
  .col-md-12.text-center
    = will_be_numbered(orders_path, @orders[:pages])

.row
  .col-md-12
    %table.table.table-striped
      %thead
        %tr
          %th.text-center
            = t(:order_number)
          %th.text-center
            = t(:user_name)
          %th.text-center
            = t(:phone)
          %th.text-center
            = t(:email)
          %th.text-center
            = t(:customer_login)
          %th.text-center
            = t(:description)
          %th.text-center
            = t(:status_description)
          %th.text-center
            = t(:order_status)
          %th.text-center
            = t(:action)

      %tbody
        - @orders[:objects].each do |o|
          %tr
            %td
              = link_to "#{o.order_name}", order_path(o)
            %td
              = o.customer_name
            %td
              = o.phone
            %td
              = o.email
            %td
              = o.customer_login
            %td.long_words_breaker
              = o.description
            %td.long_words_breaker
              = o.status_description
            %td
              = t("status_#{o.status}")
            %td
              = link_to t(:show), order_ordered_products_path(o)
              %br
              = link_to t(:edit), edit_order_path(o)

app/views/orders/show.html.haml
.row
  .col-md-12
    .page-header
      %h3.text-center
        = t(:order_title)

.row
  .col-md-8.col-md-offset-2
    .panel.panel-default
      .panel-heading
        %h3.panel-title
          %b= @order.order_name

      .panel-body
        %dl
          %dt
            = t(:user_name).to_s + ':'
          %dd
            = @order.customer_name
          %dt
            = t(:phone).to_s + ':'
          %dd
            = @order.phone
          %dt
            = t(:email).to_s + ':'
          %dd
            = @order.email
          %dt
            = t(:description).to_s + ':'
          %dd.long_words_breaker
            = @order.description
          %dt
            = t(:status_description).to_s + ':'
          %dd.long_words_breaker
            = @order.status_description
          %dt
            = t(:order_status).to_s + ':'
          %dd
            = t("status_#{@order.status}")