config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'navigation#home'

  get 'basket', to: 'navigation#basket', as: 'basket'
  get 'choice', to: 'navigation#choice', as: 'choice'

  resources :access, only: [:index, :show, :destroy, :edit, :update]

  resources :main_photos, only: [:destroy]

  resources :main_descriptions, except: [:index] do
    resources :main_photos, only: [:new, :create]
  end

  resources :categories

  resources :ordered_products, except: [:create, :index]

  resources :products do
    resources :ordered_products, only: [:create]
  end

  resources :orders, only: [:show, :index, :edit, :update, :destroy] do
    resources :ordered_products, only: [:index]
    get 'fill', on: :new
    patch 'processing', on: :collection
  end

end

app/models/category.rb
# Category
class Category < ActiveRecord::Base
  has_many :child_categories, class_name: 'Category', foreign_key: 'category_id'
  #  has_many :products

  belongs_to :parent_category, class_name: 'Category',
                               foreign_key: 'category_id'

  validates :name, presence: true, length: { maximum: 48 }
  validates :category_type, presence: true
end

app/controllers/categories_controller.rb
# Categories controller
class CategoriesController < ApplicationController
  before_action :authenticate_user!

  def new
    if current_user.admin?
      @category = Category.new
    else
      flash[:alert] = t(:operation_problem)
      redirect_to root_path
    end
  end

  def index
    if current_user.admin?
      @categories = Category.all
    else
      flash[:alert] = t(:operation_problem)
      redirect_to root_path
    end
  end

  def create
    if current_user.admin?
      @category = Category.new(attributes)
      if @category &&
         (@category.category_id.blank? ||
          @parent_category = Category.find_by('id = ?', @category.category_id))

        if @parent_category &&
           @parent_category.category_type == 'For search'
          flash.now[:alert] = t(:category_parent_type_problem)
          render 'new'
        elsif @category.category_type == 'For search' ||
              @category.category_type == 'Section name'

          if @category.save
            flash[:message] = t(:category_has_been_created)
            redirect_to categories_path
          else
            flash.now[:alert] = t(:errors_present)
            render 'new'
          end

        else
          flash.now[:alert] = t(:category_type_problem)
          render 'new'
        end
      else
        flash.now[:alert] = t(:category_parent_problem)
        render 'new'
      end
    else
      flash[:alert] = t(:operation_problem)
      redirect_to root_path
    end
  end

  def edit
    if current_user.admin?
      if @category = Category.find_by('id = ?', params[:id])
        render 'edit'
      else
        flash[:alert] = t(:category_existence_problem)
        redirect_to root_path
      end
    else
      flash[:alert] = t(:operation_problem)
      redirect_to root_path
    end
  end

  def update
    if current_user.admin?
      if @category = Category.find_by('id = ?', params[:id])
        if params[:category].is_a?(Hash)
          new_category_id = params[:category][:category_id].to_i
          new_category_type = params[:category][:category_type]

          if new_category_id == 0 || (@category.id != new_category_id &&
             Category.exists?(['id = ?', new_category_id]))

            @parent_category = Category.find_by('id = ?', new_category_id)

            if @parent_category &&
               @parent_category.category_type == 'For search'

              flash.now[:alert] = t(:category_parent_type_problem)
              render 'edit'
            elsif new_category_type == 'For search' &&
                  !@category.child_categories.blank?
              flash.now[:alert] = t(:category_has_subcategory)
              render 'edit'
            elsif new_category_type == 'For search' ||
                  new_category_type == 'Section name'

              if @category.update_attributes(attributes)
                flash[:message] = t(:category_has_been_updated)
                redirect_to categories_path
              else
                flash.now[:alert] = t(:category_update_problem)
                render 'edit'
              end

            else
              flash[:alert] = t(:category_type_problem)
              redirect_to root_path
            end
          else
            flash[:alert] = t(:category_parent_problem)
            redirect_to root_path
          end
        else
          flash[:alert] = t(:check_data)
          redirect_to root_path
        end
      else
        flash[:alert] = t(:category_existence_problem)
        redirect_to root_path
      end
    else
      flash[:alert] = t(:operation_problem)
      redirect_to root_path
    end
  end

  def destroy
    if current_user.admin?
      if @category = Category.find_by('id = ?', params[:id])
        if @category.destroy
          flash[:message] = t(:category_has_been_deleted)
          redirect_to categories_path
        else
          flash[:alert] = t(:category_delete_problem)
          redirect_to categories_path
        end
      else
        flash[:alert] = t(:category_existence_problem)
        redirect_to root_path
      end
    else
      flash[:alert] = t(:operation_problem)
      redirect_to root_path
    end
  end

  private

  def attributes
    return unless !params[:category].blank? && params[:category].is_a?(Hash)
    params.require(:category).permit(:name, :category_id, :category_type)
  end
end

app/helpers/categories_helper.rb
# Categories
module CategoriesHelper
end

app/views/categories/edit.html.slim
div class='row'
  div class='col-md-12'
    div class='page-header'
      h3 class='text-center'
        = t(:edit_category_title)

div class='row'
  div class='col-md-6 col-md-offset-3 text-center'
    = render partial: 'shared/form_errors', locals: { object: @category }

div class='row'
  div class='col-md-12'
    = form_for @category do |f|
      div class='form-group'
        = f.label :name, t(:name)
        = f.text_field :name, class: 'form-control'

      div class='form-group'
        => f.label :category_type, t(:type)
        = f.select :category_type,
                   options_for_select([[t('For search'), 'For search'],
                                       [t('Section name'), 'Section name']],
                                      @category.category_type),
                   class: 'form-control'

      div class='form-group'
        => f.label :category_id, t(:belongs_to_section)
        = f.select :category_id,
                   Category.where.not('id = ?', @category.id).pluck(:name, :id),
                   include_blank: 'None',
                   class: 'form-control'

      = f.submit t(:update), class: 'btn btn-primary'

app/views/categories/index.html.slim
div class='row'
  div class='col-md-12'
    div class='page-header'
      h3 class='text-center'
        = t(:categories_title)
        br
        span class='Title_link_new'
          = link_to t(:create_category), new_category_path

div class='row'
  div class='col-md-12'
    table class='table table-striped'
      thead
        tr
          th class='text-center'
            = t(:name)
          th class='text-center'
            = t(:type)
          th class='text-center'
            = t(:belongs_to_section)
          th class='text-center'
            = t(:action)

      tbody
        - @categories.each do |c|
          tr
            td
              = c.name
            td class='text-center'
              = t("#{c.category_type}") if c.category_type
            td class='text-center'
              = c.parent_category.name if c.parent_category
            td class='text-center'
              = link_to t(:edit), edit_category_path(c)
              br
              = link_to t(:delete), category_path(c),
                                    method: :delete,
                                    data: { confirm: t(:really_question) }

app/views/categories/new.html.slim
div class='row'
  div class='col-md-12'
    div class='page-header'
      h3 class='text-center'
        = t(:create_category_title)

div class='row'
  div class='col-md-6 col-md-offset-3 text-center'
    = render partial: 'shared/form_errors', locals: { object: @category }

div class='row'
  div class='col-md-12'
    = form_for @category do |f|
      div class='form-group'
        = f.label :name, t(:name)
        = f.text_field :name, class: 'form-control'

      div class='form-group'
        => f.label :category_type, t(:type)
        = f.select :category_type,
                   options_for_select([[t("For search"), "For search"],
                                       [t("Section name"), "Section name"]],
                                      "For search"),
                   class: 'form-control'

      div class='form-group'
        => f.label :category_id, t(:belongs_to_section)
        = f.select :category_id, Category.pluck(:name, :id),
                                 include_blank: t(:none),
                                 class: 'form-control'

      = f.submit t(:create), class: 'btn btn-primary'