config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'navigation#home'

  get 'basket', to: 'navigation#basket', as: 'basket'
  get 'choice', to: 'navigation#choice', as: 'choice'

  resources :access, only: [:index, :show, :destroy, :edit, :update]

  resources :main_photos, only: [:destroy]

  resources :main_descriptions, except: [:index] do
    resources :main_photos, only: [:new, :create]
  end

  resources :categories

  resources :ordered_products, except: [:create, :index]

  resources :products do
    resources :ordered_products, only: [:create]
  end

  resources :orders, only: [:show, :index, :edit, :update, :destroy] do
    resources :ordered_products, only: [:index]
    get 'fill', on: :new
    patch 'processing', on: :collection
  end

end

app/models/product.rb
# Product
class Product < ActiveRecord::Base
  include SharedModelMethods
  mount_uploader :photo, ProductImageUploader

  belongs_to :category

  validates :name, presence: true, length: { maximum: 48 }
  validates :description, presence: true, length: { maximum: 840 }
  validates :price, presence: true,
                    numericality: { greater_than_or_equal_to: 0 }
end

app/controllers/products_controller.rb
# Products Controller
class ProductsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]

  def new
    if current_user.admin? || current_user.manager?
      @product = Product.new
    else
      flash[:alert] = t(:product_operation_problem)
      redirect_to root_path
    end
  end

  def create
    if current_user.admin? || current_user.manager?
      @product = Product.new(attributes)
      if @product && @product.save
        flash[:message] = t(:product_has_been_added)
        redirect_to products_path
      else
        flash.now[:alert] = t(:product_add_problem)
        render 'new'
      end
    else
      flash[:alert] = t(:product_operation_problem)
      redirect_to root_path
    end
  end

  def edit
    if current_user.admin? || current_user.manager?
      @product = Product.find_by('id = ?', params[:id])
    else
      flash[:alert] = t(:product_operation_problem)
      redirect_to root_path
    end
  end

  def update
    if current_user.admin? || current_user.manager?
      @product = Product.find_by('id = ?', params[:id])
      if @product
        if @product.update_attributes(attributes)
          flash[:message] = t(:product_has_been_updated)
          redirect_to @product
        else
          flash.now[:alert] = t(:product_update_problem)
          render 'edit'
        end
      else
        flash[:alert] = t(:product_existence_problem)
        redirect_to root_path
      end
    else
      flash[:alert] = t(:product_operation_problem)
      redirect_to root_path
    end
  end

  def destroy
    if current_user.admin? || current_user.manager?
      @product = Product.find_by('id = ?', params[:id])
      if @product
        if @product.destroy
          flash[:message] = t(:product_has_been_deleted)
          redirect_to products_path
        else
          flash[:alert] = t(:product_delete_problem)
          redirect_to products_path
        end
      else
        flash[:alert] = t(:product_existence_problem)
        redirect_to root_path
      end
    else
      flash[:alert] = t(:product_operation_problem)
      redirect_to root_path
    end
  end

  def index
    @all_categories = Category.all.to_a
    @root_categories = @all_categories
                       .select { |object| object[:category_id].nil? }
    @categories = []
    recursion(@root_categories.sort_by(&:name), 0)
    @ordered_product = OrderedProduct.new

    # % - doesn't work! And check form!

    if params[:search]
      @products = Product.where('name LIKE ?',
                                "%#{params[:search]}%").numbering(params[:list],
                                                                  4, 5)
      @search = 'search=' + params[:search]
    elsif params[:category]
      @products = Product.where('category_id = ?',
                                params[:category]).numbering(params[:list],
                                                             4, 5)
      @search = 'category=' + params[:category]
    else
      @products = Product.all.numbering(params[:list], 4, 5)
    end
  end

  def show
    if @product = Product.find_by('id = ?', params[:id])
      render 'show'
    else
      flash[:alert] = t(:product_existence_problem)
      redirect_to root_path
    end
  end

  private

  def attributes
    return unless !params[:product].blank? && params[:product].is_a?(Hash)
    params.require(:product).permit(:name,
                                    :description,
                                    :category_id,
                                    :count,
                                    :price,
                                    :photo)
  end

  def recursion(root_categories, deep)
    root_categories.each do |rc|
      @categories << { object: rc, deep: deep }
      childs = @all_categories
               .select { |object| object[:category_id] == rc.id }
      recursion(childs, deep + 1)
    end
  end
end

app/helpers/products_helper.rb
# Products
module ProductsHelper
end

app/views/products/edit.html.slim
div class='row'
  div class='col-md-12'
    div class='page-header'
      h3 class='text-center'
        = t(:change_product_title)

div class='row'
  div class='col-md-12 text-center'
    = render partial: 'shared/form_errors', locals: { object: @product }

div class='row'
  div class='col-md-12'
    = form_for @product do |f|
      div class='form-group'
        = f.label :name, t(:name)
        = f.text_field :name, class: 'form-control'

      div class='form-group'
        = f.label :description, t(:description)
        = f.text_area :description, class: 'form-control', rows: '6'

      div class='form-group'
        => f.label :category_id, t(:category)
        = f.select :category_id, Category.where('category_type = ?',
                                                'For search').pluck(:name, :id),
                                 include_blank: 'None',
                                 class: 'form-control'

      div class='form-group'
        = f.label :count, t(:count)
        = f.number_field :count, class: 'form-control'

      div class='form-group'
        = f.label :price, t(:price)
        = f.number_field :price, step: 'any', class: 'form-control'

      div class='form-group'
        = f.label :photo, t(:image)
        = f.file_field :photo, class: 'form-control',
                               accept: 'image/jpeg, image/gif, image/png'

      = f.submit t(:update), class: 'btn btn-primary'

app/views/products/index.html.slim
div class='row'
  div class='col-md-12'
    div class='page-header'
      h3 class='text-center'
        = t(:products_title)
        - if user_signed_in? && \
              (current_user.admin? || current_user.manager?)
          br
          span class='Title_link_new'
            = link_to t(:add_product), new_product_path

div class='row'
  / columns are auto generated

  - a = 'first time'
  - b = 0
  - e = 1

  - @categories.each do |c|

    / if it isn't first time and privews element is deeper than current
    - if a != 'first time' && a >= c[:deep]
      - (a - c[:deep] + 1).times do
        </div>

    / if it isn't first time and current element is first in list
    - if a != 'first time' && c[:deep] == 0
      </div></div></div></div></div>

      / Each three elements must have separate block
      - if e % 3 == 0
        div class='col-md-12'
      - e+=1

    / Set open tags if the first element of list
    - if c[:deep] == 0
      <div class='col-md-4 text-center'>
        <div class='panel panel-default'>
          <div class='panel-body text-center'>
            <div class='container-fluid'>
              <div class='row'>

    / Set open tags
    = check_box_tag "make_me_#{b}", value = '1', checked = false,
                                                 class: 'MyCheckbox'
    <div class='CategoriesWrapper'>
    = label_tag "make_me_#{b}", class: 'checkbox_label' do
      - if c[:object][:category_type] == 'For search'
        = link_to(c[:object][:name], products_path(category: c[:object][:id]))
      - else
        = c[:object][:name]

    / Set variables: count of tags id and previews element deep
    - b+=1
    - a = c[:deep]

    / Set close tags if the last element of list
    - if c == @categories.last
      - (c[:deep] + 1 ).times do
        </div>

      </div></div></div></div></div>

div class='row'
  div class='col-md-12 text-center'
    = will_be_numbered(products_path, @products[:pages], @search)

table class='table table-striped'
  thead
    tr
      th class='text-center'
        = t(:image)
      th class='text-center'
        = t(:name)
      th class='text-center'
        = t(:description)
      th class='text-center'
        = t(:category)
      th class='text-center'
        = t(:price)
      - if user_signed_in? && !current_user.customer?
        th class='text-center'
          = t(:count)
        th class='text-center'
          = t(:action)

      th class='text-center'
        = t(:order)

  tbody
    - @products[:objects].each do |p|
      tr
        td
          = image_tag p.photo.url, class: 'img-rounded MyImageSize'
        td
          = link_to "#{p.name}", product_path(p)
        td class='long_words_breaker'
          = p.description
        td class='text-center'
          - name = @all_categories \
                    .select { |object| object[:id] == p.category_id }
          = name.first.name if name.first
        td class='text-center'
          = p.price

        - if user_signed_in? && !current_user.customer?
          td class='text-center'
            = p.count
          td class='text-center'
            = link_to t(:edit), edit_product_path(p)
            br
            = link_to t(:delete), product_path(p),
                                  method: :delete,
                                  data: { confirm: 'Realy?' }

        td class='text-center'

          = form_for(@ordered_product,
                     url: product_ordered_products_path(p.id),
                     :html => { class: 'form-inline MyFormSize' }) do |f|
            div class='form-group'
              = f.label :count, class: 'sr-only'
              = f.number_field :count,
                               value: '1',
                               min: '1',
                               class: 'form-control text-center'
            br
            br
            = f.submit t(:add_to_basket), class: 'btn btn-primary'

app/views/products/new.html.slim
div class='row'
  div class='col-md-12'
    div class='page-header'
      h3 class='text-center'
        = t(:create_product)

div class='row'
  div class='col-md-12 text-center'
    = render partial: 'shared/form_errors', locals: { object: @product }

div class='row'
  div class='col-md-12'
    = form_for @product do |f|
      div class='form-group'
        = f.label :name, t(:name)
        = f.text_field :name, class: 'form-control'

      div class='form-group'
        = f.label :description, t(:description)
        = f.text_area :description, class: 'form-control', rows: '6'

      div class='form-group'
        => f.label :category_id, t(:category)
        = f.select :category_id, Category.where('category_type = ?',
                                                'For search').pluck(:name, :id),
                                 include_blank: t(:none),
                                 class: 'form-control'

      div class='form-group'
        = f.label :count, t(:count)
        = f.number_field :count, class: 'form-control'

      div class='form-group'
        = f.label :price, t(:price)
        = f.number_field :price, step: 'any', class: 'form-control'

      div class='form-group'
        = f.label :photo, t(:image)
        = f.file_field :photo, class: 'form-control',
                               accept: 'image/jpeg, image/gif, image/png'

      = f.submit t(:create), class: 'btn btn-primary'

app/views/products/show.html.slim
div class='row'
  div class='col-md-12'
    div class='page-header'
      h3 class='text-center'
        = "#{@product.name}"
        br
        span class='Title_link_new'
          = link_to t(:all_products), products_path

table class='table table-striped'
  thead
    tr
      th class='text-center'
        = t(:image)
      th class='text-center'
        = t(:name)
      th class='text-center'
        = t(:description)
      th class='text-center'
        = t(:category)
      th class='text-center'
        = t(:price)
      th class='text-center'
        = t(:count)

      - if user_signed_in?
        th class='text-center'
          = t(:action)

  tbody
    tr
      td
        = image_tag @product.photo.url, class: 'img-rounded MyImageSize'
      td
        = "#{@product.name}"
      td class='long_words_breaker'
        = @product.description
      td class='text-center'
        - name = Category \
                 .select { |object| object[:id] == @product.category_id }
        = name.first.name if name.first
      td class='text-center'
        = @product.price
      td class='text-center'
        = @product.count
      - if user_signed_in?
        td class='text-center'
          => link_to t(:edit), edit_product_path(@product)
          = link_to t(:delete), product_path(@product),
                                method: :delete,
                                data: { confirm: t(:really_question) }