config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'navigation#home'

  get 'basket', to: 'navigation#basket', as: 'basket'
  get 'choice', to: 'navigation#choice', as: 'choice'

  resources :access, only: [:index, :show, :destroy, :edit, :update]

  resources :main_photos, only: [:destroy]

  resources :main_descriptions, except: [:index] do
    resources :main_photos, only: [:new, :create]
  end

  resources :categories

  resources :ordered_products, except: [:create, :index]

  resources :products do
    resources :ordered_products, only: [:create]
  end

  resources :orders, only: [:show, :index, :edit, :update, :destroy] do
    resources :ordered_products, only: [:index]
    get 'fill', on: :new
    patch 'processing', on: :collection
  end

end

app/controllers/navigation_controller.rb
# Navigation Controller
class NavigationController < ApplicationController
  def home
    @main_descriptions = MainDescription.all
  end

  def basket
    if @order = Order.find_by('customer_id = ? and status = ?',
                              cookies.signed[:customer_token],
                              Order.statuses[:opened])
      redirect_to order_ordered_products_path(@order)
    else
      flash[:message] = t(:basket_is_empty)
      redirect_to products_path
    end
  end

  def choice
    if @order = Order.find_by('customer_id = ? and status = ?',
                              cookies.signed[:customer_token],
                              Order.statuses[:opened])

      if user_signed_in?
        redirect_to fill_new_order_path
      else
        render 'choice'
      end

    else
      flash[:message] = t(:basket_is_empty)
      redirect_to products_path
    end
  end
end

app/helpers/navigation_helper.rb
# Navigation
module NavigationHelper
end

app/views/navigation/choice.html.slim
div class='row'
  div class='col-md-12'
    div class='page-header'
      h3 class='text-center'
        = t(:choice)

div class='row'
  div class='col-md-12'
    table class='table table-striped'
      thead
        tr
          th
            = t(:leave_information)
      tbody
        tr
          td
            = link_to t(:easy_way), fill_new_order_path

div class='row'
  div class='col-md-12'
    table class='table table-striped'
      thead
        tr
          th
            = t(:register_or_login)
      tbody
        tr
          td
            = link_to t(:right_way), new_user_session_path

app/views/navigation/home.html.slim
div class='row'
  div class='col-md-12'
    div class='page-header'
      h3 class='text-center'
        = t(:about_us)

- @main_descriptions.each do |md|

  div class='row'
    div class='col-md-12'

      - if md.title
        h4
          strong
            = md.title

      p
        = md.description

  div class='row'
    - md.main_photos.each do |p|
      div class='col-md-3'
        div class='MyImageFrame'

          = image_tag p.photo.url, class: 'img-rounded MyImageSize'
          - if user_signed_in? && current_user.admin?
            br

            = link_to t(:delete), main_photo_path(p),
                                  method: :delete,
                                  data: {confirm: t(:really_question)}

  - if user_signed_in? && current_user.admin?
    div class='row'
      div class='col-md-12 text-center'

        ul class='pager'
          li
            => link_to t(:edit), edit_main_description_path(md)
          li
            => link_to t(:delete), main_description_path(md),
                                  method: :delete,
                                  data: {confirm: t(:really_question)}
          li
            = link_to t(:add_photo), new_main_description_main_photo_path(md)

        hr

- if user_signed_in? && current_user.admin?
  div class='row'
    div class='col-md-12 text-center'
      ul class='pager'
        li
          = link_to t(:add_description), new_main_description_path
      hr
div class='row'
  div class='col-md-12'
    - content_for :google_map do
      = javascript_include_tag \
         "http://maps.google.com/maps/api/js?sensor=false&language=ru"

    = javascript_tag "googlemap(\"#{t(:map_text)}\");"

div class='row'
  div class='col-md-12'
    br
    div class='map' id='map' data-no-turbolink=true